export type AssetReference = { src: string; alt: string; caption?: string; context?: string; previewFit?: 'contain' | 'cover' | 'natural'; previewPosition?: string }
export type ProjectLink = { label: string; href: string }
export type CaseStudy = { slug: string; title: string; number?: string; projectType?: string; category?: string; featured?: boolean; summary?: string; overview?: string; contributions?: string[]; features?: string[]; outcome?: string; technologies?: string[]; visuals?: AssetReference[]; gallery?: AssetReference[]; links?: ProjectLink[]; certificateLink?: ProjectLink }
export type Certification = { slug: string; title: string; organization: string; description: string; visual?: AssetReference; relatedLink?: ProjectLink }
export type ExperienceContentBlock = { label: string; description: string }
export type ExperienceHighlight = { title: string; description: string; href: string; linkLabel: string }
export type Experience = { company: string; role: string; period: string; location: string; contentBlocks: ExperienceContentBlock[]; highlights?: ExperienceHighlight[]; visual?: AssetReference; certificateLink?: ProjectLink }
export type StartupExperience = { label: string; company: string; description: string; href?: string; linkLabel?: string; visual?: AssetReference }
export type ProfessionalContact = { name: string; title: string; href: string }
export type AdditionalProject = { title: string; kind: 'Graduation' | 'Bootcamp' | 'Personal'; summary?: string; technologies?: string[]; visual?: AssetReference; links?: ProjectLink[] }
export type Capability = { title: string; description?: string }
export type SiteDetails = { name: string; role: string; email?: string; links?: ProjectLink[]; peopleWorkedWith?: ProfessionalContact[]; resumeUrl?: string }
