export type AssetReference = { src: string; alt: string; caption?: string; context?: string; previewFit?: 'contain' | 'cover' | 'natural'; previewPosition?: string }
export type ProjectLink = { label: string; href: string }
export type CaseStudyArchitecturePath = { label: string; items: string[] }
export type CaseStudyArchitecture = { title?: string; description?: string; items?: string[]; paths?: CaseStudyArchitecturePath[]; fallback?: string }
export type TechnicalDetail = { title: string; description: string }
export type CaseStudyVisualSection = { title: string; description?: string; visual: AssetReference }
export type CaseStudy = { slug: string; title: string; number?: string; projectType?: string; category?: string; featured?: boolean; summary?: string; overview?: string; problem?: string; goal?: string; approach?: string[]; contributions?: string[]; features?: string[]; story?: string; solution?: string; architecture?: CaseStudyArchitecture; technicalDetails?: TechnicalDetail[]; challenges?: string[]; outcome?: string; technologies?: string[]; visuals?: AssetReference[]; gallery?: AssetReference[]; visualSections?: CaseStudyVisualSection[]; links?: ProjectLink[] }
export type ExperienceContentBlock = { label: string; description: string }
export type ExperienceHighlight = { title: string; description: string; href: string; linkLabel: string }
export type Experience = { company: string; role: string; period: string; location: string; contentBlocks: ExperienceContentBlock[]; highlights?: ExperienceHighlight[] }
export type StartupExperience = { label: string; company: string; description: string; href?: string; linkLabel?: string }
export type ProfessionalContact = { name: string; title: string; href: string }
export type AdditionalProject = { title: string; kind: 'Graduation' | 'Bootcamp' | 'Personal'; summary?: string; technologies?: string[]; visual?: AssetReference; links?: ProjectLink[] }
export type Capability = { title: string; description?: string }
export type SiteDetails = { name: string; role: string; email?: string; links?: ProjectLink[]; peopleWorkedWith?: ProfessionalContact[]; resumeUrl?: string }
